import { Skin, LevelConfig, DailyChallenge } from '../types/game';

export const SKINS: Skin[] = [
  // --- COMMON (4 Skins) ---
  {
    id: 'amber',
    name: 'Amber',
    rarity: 'Common',
    color: '#3b82f6',
    secondaryColor: '#bfdbfe',
    glowColor: 'rgba(59, 130, 246, 0.7)',
    trailColor: 'rgba(96, 165, 250, 0.4)',
    description: 'Precision amber cyber tracker infused with high-frequency pheromones.',
    unlockedByDefault: true,
    cost: 0,
  },
  {
    id: 'golden_amber',
    name: 'Gold',
    rarity: 'Common',
    color: '#f59e0b',
    secondaryColor: '#fef3c7',
    glowColor: 'rgba(245, 158, 11, 0.7)',
    trailColor: 'rgba(251, 191, 36, 0.4)',
    description: 'Natural hardened amber resin with golden hexagonal bio-luminescence.',
    unlockedByDefault: false,
    cost: 100,
  },
  {
    id: 'crimson',
    name: 'Crimson',
    rarity: 'Common',
    color: '#ef4444',
    secondaryColor: '#fee2e2',
    glowColor: 'rgba(239, 68, 68, 0.7)',
    trailColor: 'rgba(248, 113, 113, 0.5)',
    description: 'Blazing soldier ant pheromone essence that burns with blood rage.',
    unlockedByDefault: false,
    cost: 150,
  },
  {
    id: 'forest_moss',
    name: 'Moss',
    rarity: 'Common',
    color: '#15803d',
    secondaryColor: '#dcfce7',
    glowColor: 'rgba(21, 128, 61, 0.7)',
    trailColor: 'rgba(34, 197, 94, 0.4)',
    description: 'Camouflaged forest bark with natural spore-cloud dispersion.',
    unlockedByDefault: false,
    cost: 200,
  },

  // --- RARE (5 Skins) ---
  {
    id: 'cyan',
    name: 'Cyan',
    rarity: 'Rare',
    color: '#06b6d4',
    secondaryColor: '#cffafe',
    glowColor: 'rgba(6, 182, 212, 0.75)',
    trailColor: 'rgba(34, 211, 238, 0.5)',
    description: 'Experimental cybernetic hive matrix tracking cursor.',
    unlockedByDefault: false,
    cost: 300,
  },
  {
    id: 'toxic',
    name: 'Toxic',
    rarity: 'Rare',
    color: '#10b981',
    secondaryColor: '#d1fae5',
    glowColor: 'rgba(168, 85, 247, 0.75)',
    trailColor: 'rgba(52, 211, 153, 0.5)',
    description: 'Corrosive formic acid vapor dripping with lethal bio-hazard energy.',
    unlockedByDefault: false,
    cost: 350,
  },
  {
    id: 'amethyst',
    name: 'Amethyst',
    rarity: 'Rare',
    color: '#a855f7',
    secondaryColor: '#f3e8ff',
    glowColor: 'rgba(168, 85, 247, 0.75)',
    trailColor: 'rgba(192, 132, 252, 0.5)',
    description: 'Supreme subterranean queen aura radiating mystical void energy.',
    unlockedByDefault: false,
    cost: 400,
  },
  {
    id: 'solar_flare',
    name: 'Solar',
    rarity: 'Rare',
    color: '#f97316',
    secondaryColor: '#ffedd5',
    glowColor: 'rgba(249, 115, 22, 0.75)',
    trailColor: 'rgba(251, 146, 60, 0.5)',
    description: 'Thermonuclear heat core that leaves trailing solar plasma ripples.',
    unlockedByDefault: false,
    cost: 450,
  },
  {
    id: 'glacial_cryo',
    name: 'Glacial',
    rarity: 'Rare',
    color: '#38bdf8',
    secondaryColor: '#e0f2fe',
    glowColor: 'rgba(56, 189, 248, 0.75)',
    trailColor: 'rgba(125, 211, 252, 0.5)',
    description: 'Sub-zero cryo frost crystals that chill surrounding dirt particles.',
    unlockedByDefault: false,
    cost: 500,
  },

  // --- EPIC (6 Skins) ---
  {
    id: 'emerald_matrix',
    name: 'Emerald',
    rarity: 'Epic',
    color: '#22c55e',
    secondaryColor: '#dcfce7',
    glowColor: 'rgba(34, 197, 94, 0.8)',
    trailColor: 'rgba(74, 222, 128, 0.5)',
    description: 'High-frequency digital code stream pulsing through synthetic insect veins.',
    unlockedByDefault: false,
    cost: 550,
  },
  {
    id: 'obsidian_shadow',
    name: 'Obsidian',
    rarity: 'Epic',
    color: '#94a3b8',
    secondaryColor: '#f1f5f9',
    glowColor: 'rgba(148, 163, 184, 0.8)',
    trailColor: 'rgba(203, 213, 225, 0.4)',
    description: 'Stealth volcanic glass forged in subterranean fissures to absorb light.',
    unlockedByDefault: false,
    cost: 600,
  },
  {
    id: 'synthwave_pink',
    name: 'Synthwave',
    rarity: 'Epic',
    color: '#ec4899',
    secondaryColor: '#fce7f3',
    glowColor: 'rgba(236, 72, 153, 0.8)',
    trailColor: 'rgba(244, 114, 182, 0.5)',
    description: 'Retro-futuristic neon highway grid radiating high-energy synth pulses.',
    unlockedByDefault: false,
    cost: 650,
  },
  {
    id: 'electric_volt',
    name: 'Volt',
    rarity: 'Epic',
    color: '#eab308',
    secondaryColor: '#fef9c3',
    glowColor: 'rgba(234, 179, 8, 0.85)',
    trailColor: 'rgba(250, 204, 21, 0.6)',
    description: 'Arcing electrostatic discharges dancing across hyper-sensitive antennae.',
    unlockedByDefault: false,
    cost: 700,
  },
  {
    id: 'radioactive_waste',
    name: 'Hazard',
    rarity: 'Epic',
    color: '#84cc16',
    secondaryColor: '#ecfccb',
    glowColor: 'rgba(132, 204, 22, 0.85)',
    trailColor: 'rgba(163, 230, 53, 0.6)',
    description: 'Unstable isotope radiation dripping with glowing bio-mutagen essence.',
    unlockedByDefault: false,
    cost: 750,
  },
  {
    id: 'magma_core',
    name: 'Magma',
    rarity: 'Epic',
    color: '#dc2626',
    secondaryColor: '#fee2e2',
    glowColor: 'rgba(220, 38, 38, 0.85)',
    trailColor: 'rgba(239, 68, 68, 0.6)',
    description: 'Molten magma shell flowing with liquid basalt and micro-eruptions.',
    unlockedByDefault: false,
    cost: 800,
  },

  // --- LEGENDARY (5 Skins) ---
  {
    id: 'chrono_brass',
    name: 'Chrono',
    rarity: 'Legendary',
    color: '#d97706',
    secondaryColor: '#fef3c7',
    glowColor: 'rgba(217, 119, 6, 0.85)',
    trailColor: 'rgba(245, 158, 11, 0.55)',
    description: 'Intricate brass clockwork gears ticking in synchrony with level BPM.',
    unlockedByDefault: false,
    cost: 900,
  },
  {
    id: 'ghost_phantom',
    name: 'Ghost',
    rarity: 'Legendary',
    color: '#e2e8f0',
    secondaryColor: '#ffffff',
    glowColor: 'rgba(226, 232, 240, 0.85)',
    trailColor: 'rgba(248, 250, 252, 0.6)',
    description: 'Ethereal spectral projection phasing through physical terrarium boundaries.',
    unlockedByDefault: false,
    cost: 950,
  },
  {
    id: 'blood_moon',
    name: 'Blood',
    rarity: 'Legendary',
    color: '#b91c1c',
    secondaryColor: '#fecaca',
    glowColor: 'rgba(185, 28, 28, 0.85)',
    trailColor: 'rgba(220, 38, 38, 0.6)',
    description: 'Occult crimson moon aura invoking the ferocity of ancient ant broods.',
    unlockedByDefault: false,
    cost: 1000,
  },
  {
    id: 'deep_nebula',
    name: 'Nebula',
    rarity: 'Legendary',
    color: '#6366f1',
    secondaryColor: '#e0e7ff',
    glowColor: 'rgba(99, 102, 241, 0.85)',
    trailColor: 'rgba(129, 140, 248, 0.6)',
    description: 'Swirling stellar dust and birthplaces of cosmic ant dynasties.',
    unlockedByDefault: false,
    cost: 1100,
  },
  {
    id: 'quantum_pulsar',
    name: 'Pulsar',
    rarity: 'Legendary',
    color: '#8b5cf6',
    secondaryColor: '#ede9fe',
    glowColor: 'rgba(139, 92, 246, 0.9)',
    trailColor: 'rgba(167, 139, 250, 0.6)',
    description: 'High-energy gamma beam emitter spinning at blinding rotational velocity.',
    unlockedByDefault: false,
    cost: 1200,
  },

  // --- MYTHIC (4 Skins) ---
  {
    id: 'aurora_spirit',
    name: 'Aurora',
    rarity: 'Mythic',
    color: '#2dd4bf',
    secondaryColor: '#ccfbf1',
    glowColor: 'rgba(45, 212, 191, 0.9)',
    trailColor: 'rgba(94, 234, 212, 0.65)',
    description: 'Celestial geomagnetic curtain waving with luminous teal and emerald radiance.',
    unlockedByDefault: false,
    cost: 1400,
  },
  {
    id: 'carbon_titanium',
    name: 'Titanium',
    rarity: 'Mythic',
    color: '#64748b',
    secondaryColor: '#e2e8f0',
    glowColor: 'rgba(100, 116, 139, 0.9)',
    trailColor: 'rgba(148, 163, 184, 0.65)',
    description: 'Aerospace-grade composite weave reinforced with nano-diamond coatings.',
    unlockedByDefault: false,
    cost: 1600,
  },
  {
    id: 'queen_regalia',
    name: 'Queen',
    rarity: 'Mythic',
    color: '#f43f5e',
    secondaryColor: '#ffe4e6',
    glowColor: 'rgba(244, 63, 94, 0.95)',
    trailColor: 'rgba(251, 113, 133, 0.7)',
    description: 'The ceremonial crown of the colony sovereign, carved from crystalline chitin.',
    unlockedByDefault: false,
    cost: 1800,
  },
  {
    id: 'celestial_sovereign',
    name: 'Celestial',
    rarity: 'Mythic',
    color: '#fbbf24',
    secondaryColor: '#fffbeb',
    glowColor: 'rgba(251, 191, 36, 0.95)',
    trailColor: 'rgba(253, 224, 71, 0.7)',
    description: 'Apex divine transcendence. Golden starlight wings granting supreme colony mastery.',
    unlockedByDefault: false,
    cost: 2000,
  },
  {
    id: 'dark_singularity',
    name: 'Singularity',
    rarity: 'Mythic',
    color: '#818cf8',
    secondaryColor: '#e0e7ff',
    glowColor: 'rgba(129, 140, 248, 0.95)',
    trailColor: 'rgba(99, 102, 241, 0.75)',
    description: 'Gravitational event horizon collapsing light into an impenetrable void vortex.',
    unlockedByDefault: false,
    cost: 2200,
  },
  {
    id: 'hyper_drive',
    name: 'Hyperdrive',
    rarity: 'Mythic',
    color: '#06b6d4',
    secondaryColor: '#cffafe',
    glowColor: 'rgba(6, 182, 212, 0.95)',
    trailColor: 'rgba(34, 211, 238, 0.75)',
    description: 'Faster-than-light tachyon drive projecting relativistic quantum trails.',
    unlockedByDefault: false,
    cost: 2400,
  },
  {
    id: 'prism_rainbow',
    name: 'Prism',
    rarity: 'Legendary',
    color: '#ec4899',
    secondaryColor: '#fdf2f8',
    glowColor: 'rgba(236, 72, 153, 0.9)',
    trailColor: 'rgba(244, 114, 182, 0.65)',
    description: 'Refractive diamond facet splitting pure white photons into a rainbow spectrum.',
    unlockedByDefault: false,
    cost: 1300,
  },
  {
    id: 'bio_nanite',
    name: 'Nanite',
    rarity: 'Epic',
    color: '#67e8f9',
    secondaryColor: '#ecfeff',
    glowColor: 'rgba(103, 232, 249, 0.85)',
    trailColor: 'rgba(165, 243, 252, 0.6)',
    description: 'Self-replicating microscopic cyber-nanites assembling instant force-fields.',
    unlockedByDefault: false,
    cost: 850,
  },
];

export const DAILY_CHALLENGES: DailyChallenge[] = [
  {
    id: 'daily_dodge',
    title: 'Swarm Evasion',
    description: 'Dodge 100 ants in close proximity across any level runs.',
    type: 'dodge_ants',
    targetCount: 100,
    rewardPts: 1000,
    rewardSugar: 50,
    iconName: 'ShieldAlert',
  },
  {
    id: 'daily_sugar',
    title: 'Sweet Sugar Harvest',
    description: 'Collect 20 glowing sugar cubes during gameplay.',
    type: 'collect_sugar',
    targetCount: 20,
    rewardPts: 1000,
    rewardSugar: 60,
    iconName: 'Cookie',
  },
  {
    id: 'daily_portals',
    title: 'Tempo Warp Navigator',
    description: 'Enter 8 speed portals (0.5x, 1.5x, 2.0x) to manipulate level tempo.',
    type: 'speed_portals',
    targetCount: 8,
    rewardPts: 1250,
    rewardSugar: 75,
    iconName: 'Zap',
  },
  {
    id: 'daily_hard_clear',
    title: 'Apex Colony Breach',
    description: 'Survive and complete any chamber of Hard, Harder, Insane, or Crazy difficulty.',
    type: 'beat_hard',
    targetCount: 1,
    rewardPts: 1500,
    rewardSugar: 100,
    iconName: 'Trophy',
  },
  {
    id: 'daily_freemode',
    title: 'Endless Free Mode Endurance',
    description: 'Survive 35+ seconds in Endless Free Mode as difficulties randomize every 15s.',
    type: 'survive_free_mode',
    targetCount: 35,
    rewardPts: 2000,
    rewardSugar: 150,
    iconName: 'Flame',
  },
  {
    id: 'daily_score_blitz',
    title: 'Score Blitz Master',
    description: 'Achieve at least 5,000 PTS in a single level run.',
    type: 'score_milestone',
    targetCount: 5000,
    rewardPts: 2500,
    rewardSugar: 200,
    iconName: 'Award',
  },
];

export const DIFFICULTY_COLORS: Record<string, string> = {
  Easy: '#38bdf8', // Light Cyan/Blue
  Normal: '#3b82f6', // Solid Blue
  Hard: '#2563eb', // Royal Blue
  Harder: '#818cf8', // Indigo
  Insane: '#c084fc', // Purple
  Crazy: '#f43f5e', // Hot Crimson
};

export const LEVELS: LevelConfig[] = [
  // --- EASY (4 Levels) ---
  {
    id: 1,
    name: 'Happiness',
    difficulty: 'Easy',
    difficultyColor: '#38bdf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1622289',
    songTitle: 'Happiness',
    artist: 'Newgrounds #1622289',
    bpm: 124,
    durationSeconds: 65,
    themeColor: '#38bdf8',
    bgColor: '#061325',
    description: 'Colony awakening. Learn to dodge worker ant swarms and gentle shifting portals.',
    spawnerCount: 2,
    maxAnts: 35,
    mechanicId: 'nuke_houses',
    mechanicName: 'nuke houses',
    mechanicHint: 'click anthills 3 times to nuke them & vaporize nearby ants',
  },
  {
    id: 2,
    name: 'Sunny Meadow',
    difficulty: 'Easy',
    difficultyColor: '#38bdf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1622290',
    songTitle: 'Sunny Meadow',
    artist: 'Newgrounds #1622290',
    bpm: 122,
    durationSeconds: 65,
    themeColor: '#60a5fa',
    bgColor: '#08172e',
    description: 'Gentle breeze across the terrarium surface. Worker scouts move in predictable packs.',
    spawnerCount: 2,
    maxAnts: 40,
    mechanicId: 'sugar_geysers',
    mechanicName: 'sugar geysers',
    mechanicHint: 'click bubbling geysers to blast sugar shockwaves & push ants',
  },
  {
    id: 3,
    name: 'Ant Trail',
    difficulty: 'Easy',
    difficultyColor: '#38bdf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1621000',
    songTitle: 'Ant Trail',
    artist: 'Newgrounds #1621000',
    bpm: 126,
    durationSeconds: 70,
    themeColor: '#38bdf8',
    bgColor: '#091a33',
    description: 'Pheromone trail tracking. Dodge small scout patrols circling around sugar cubes.',
    spawnerCount: 2,
    maxAnts: 42,
    mechanicId: 'emp_pods',
    mechanicName: 'emp pods',
    mechanicHint: 'click glowing emp orbs to freeze the entire colony for 3s',
  },
  {
    id: 4,
    name: 'Pebble Path',
    difficulty: 'Easy',
    difficultyColor: '#38bdf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1619500',
    songTitle: 'Pebble Path',
    artist: 'Newgrounds #1619500',
    bpm: 128,
    durationSeconds: 70,
    themeColor: '#60a5fa',
    bgColor: '#061226',
    description: 'Graduation from the surface. Introducing floating speed portals into the mix.',
    spawnerCount: 3,
    maxAnts: 45,
    mechanicId: 'warp_gates',
    mechanicName: 'speed warps',
    mechanicHint: 'pass speed portals to blast pursuing ants with shockwaves',
  },

  // --- NORMAL (4 Levels) ---
  {
    id: 5,
    name: "Dawn'n'Drive",
    difficulty: 'Normal',
    difficultyColor: '#3b82f6',
    songUrl: 'https://www.newgrounds.com/audio/listen/1616642',
    songTitle: "Dawn'n'Drive",
    artist: 'Newgrounds #1616642',
    bpm: 138,
    durationSeconds: 75,
    themeColor: '#3b82f6',
    bgColor: '#07162c',
    description: 'Twilight road through the dirt tunnels. Rapid worker packs and moving buzzsaw hazards.',
    spawnerCount: 3,
    maxAnts: 55,
    mechanicId: 'honey_traps',
    mechanicName: 'honey traps',
    mechanicHint: 'click honey nodes to glue and slow down surrounding ants',
  },
  {
    id: 6,
    name: 'Midnight Run',
    difficulty: 'Normal',
    difficultyColor: '#3b82f6',
    songUrl: 'https://www.newgrounds.com/audio/listen/1615500',
    songTitle: 'Midnight Run',
    artist: 'Newgrounds #1615500',
    bpm: 136,
    durationSeconds: 75,
    themeColor: '#2563eb',
    bgColor: '#081730',
    description: 'Pitch darkness within the lower tunnels. Ants accelerate as the rhythm builds up.',
    spawnerCount: 3,
    maxAnts: 58,
    mechanicId: 'sonic_pulse',
    mechanicName: 'sonic pulse',
    mechanicHint: 'click anywhere to emit sonic shockwaves repelling nearby ants',
  },
  {
    id: 7,
    name: 'Tunnel Rush',
    difficulty: 'Normal',
    difficultyColor: '#3b82f6',
    songUrl: 'https://www.newgrounds.com/audio/listen/1615200',
    songTitle: 'Tunnel Rush',
    artist: 'Newgrounds #1615200',
    bpm: 140,
    durationSeconds: 80,
    themeColor: '#3b82f6',
    bgColor: '#06142a',
    description: 'Narrow corridors with double buzzsaws ricocheting from side to side.',
    spawnerCount: 3,
    maxAnts: 62,
    mechanicId: 'laser_breaker',
    mechanicName: 'laser nodes',
    mechanicHint: 'click laser emitters to disable them for 6 seconds',
  },
  {
    id: 8,
    name: 'Dust & Grit',
    difficulty: 'Normal',
    difficultyColor: '#3b82f6',
    songUrl: 'https://www.newgrounds.com/audio/listen/1615000',
    songTitle: 'Dust & Grit',
    artist: 'Newgrounds #1615000',
    bpm: 142,
    durationSeconds: 80,
    themeColor: '#60a5fa',
    bgColor: '#091c38',
    description: 'Heavy sandstorms blow across the nest, accelerating ant movement bursts.',
    spawnerCount: 4,
    maxAnts: 65,
    mechanicId: 'pheromone_bait',
    mechanicName: 'pheromone bait',
    mechanicHint: 'click to deploy sugar bait that lures all ants away',
  },

  // --- HARD (4 Levels) ---
  {
    id: 9,
    name: 'Experience',
    difficulty: 'Hard',
    difficultyColor: '#2563eb',
    songUrl: 'https://www.newgrounds.com/audio/listen/1614871',
    songTitle: 'Experience',
    artist: 'Newgrounds #1614871',
    bpm: 150,
    durationSeconds: 85,
    themeColor: '#2563eb',
    bgColor: '#0a1738',
    description: 'Deep crystal cavern. Relentless soldier ants, laser beam barriers, and frequent speed portals.',
    spawnerCount: 4,
    maxAnts: 75,
    mechanicId: 'fire_extinguisher',
    mechanicName: 'fire extinguish',
    mechanicHint: 'click blazing fire ant nests to douse flames & clear embers',
  },
  {
    id: 10,
    name: 'Quartz Cavern',
    difficulty: 'Hard',
    difficultyColor: '#2563eb',
    songUrl: 'https://www.newgrounds.com/audio/listen/1613500',
    songTitle: 'Quartz Cavern',
    artist: 'Newgrounds #1613500',
    bpm: 152,
    durationSeconds: 85,
    themeColor: '#3b82f6',
    bgColor: '#081432',
    description: 'Resonating quartz crystals emit sonic laser beams synchronized to the bass kick.',
    spawnerCount: 4,
    maxAnts: 80,
    mechanicId: 'orbital_blast',
    mechanicName: 'orbital strikes',
    mechanicHint: 'click targeting reticles to call orbital blast strikes',
  },
  {
    id: 11,
    name: 'Subterranean',
    difficulty: 'Hard',
    difficultyColor: '#2563eb',
    songUrl: 'https://www.newgrounds.com/audio/listen/1612000',
    songTitle: 'Subterranean',
    artist: 'Newgrounds #1612000',
    bpm: 154,
    durationSeconds: 90,
    themeColor: '#1d4ed8',
    bgColor: '#06102a',
    description: 'Acid spitting ants join the horde. Stay mobile to avoid expanding corrosive puddles.',
    spawnerCount: 4,
    maxAnts: 85,
    mechanicId: 'gravity_core',
    mechanicName: 'gravity well',
    mechanicHint: 'click gravity core to pull & crush nearby swarm in an implosion',
  },
  {
    id: 12,
    name: 'Iron Mandible',
    difficulty: 'Hard',
    difficultyColor: '#2563eb',
    songUrl: 'https://www.newgrounds.com/audio/listen/1610000',
    songTitle: 'Iron Mandible',
    artist: 'Newgrounds #1610000',
    bpm: 155,
    durationSeconds: 90,
    themeColor: '#2563eb',
    bgColor: '#09153a',
    description: 'Armored soldier ants with increased mass and tighter pursuit angles.',
    spawnerCount: 5,
    maxAnts: 90,
    mechanicId: 'shield_battery',
    mechanicName: 'shield battery',
    mechanicHint: 'click glowing power cells to trigger an invulnerable shield burst',
  },

  // --- HARDER (4 Levels) ---
  {
    id: 13,
    name: 'Dying to Live',
    difficulty: 'Harder',
    difficultyColor: '#818cf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1607400',
    songTitle: 'Dying to Live',
    artist: 'Newgrounds #1607400',
    bpm: 162,
    durationSeconds: 95,
    themeColor: '#818cf8',
    bgColor: '#101438',
    description: 'Molten magma anthill. Fire ants bursting from all directions, hyper portals, and laser fields.',
    spawnerCount: 5,
    maxAnts: 100,
    mechanicId: 'queen_cocoons',
    mechanicName: 'queen cocoons',
    mechanicHint: 'spam-click brood cocoons before they hatch into titans',
  },
  {
    id: 14,
    name: 'Magma Chamber',
    difficulty: 'Harder',
    difficultyColor: '#818cf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1606200',
    songTitle: 'Magma Chamber',
    artist: 'Newgrounds #1606200',
    bpm: 164,
    durationSeconds: 95,
    themeColor: '#6366f1',
    bgColor: '#0d1133',
    description: 'Scorching thermal vents create periodic turbulence while ants lunge in packs.',
    spawnerCount: 5,
    maxAnts: 105,
    mechanicId: 'tesla_coils',
    mechanicName: 'tesla coils',
    mechanicHint: 'click electric pylons to chain lightning through the swarm',
  },
  {
    id: 15,
    name: 'Red Alert Colony',
    difficulty: 'Harder',
    difficultyColor: '#818cf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1605000',
    songTitle: 'Red Alert Colony',
    artist: 'Newgrounds #1605000',
    bpm: 166,
    durationSeconds: 100,
    themeColor: '#818cf8',
    bgColor: '#11163d',
    description: 'Alarm klaxons sound across the queen chamber. Dual laser grids criss-cross the floor.',
    spawnerCount: 5,
    maxAnts: 110,
    mechanicId: 'quake_fissure',
    mechanicName: 'seismic faults',
    mechanicHint: 'click seismic lines to trigger ant-clearing cave-ins',
  },
  {
    id: 16,
    name: 'Formic Storm',
    difficulty: 'Harder',
    difficultyColor: '#818cf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1604000',
    songTitle: 'Formic Storm',
    artist: 'Newgrounds #1604000',
    bpm: 168,
    durationSeconds: 100,
    themeColor: '#6366f1',
    bgColor: '#0e1236',
    description: 'Massive acid density. Weave between saw blades while maintaining safe cursor velocity.',
    spawnerCount: 6,
    maxAnts: 115,
    mechanicId: 'acid_geysers',
    mechanicName: 'acid geysers',
    mechanicHint: 'click bubbling vents to purge corrosive acid outward',
  },

  // --- INSANE (4 Levels) ---
  {
    id: 17,
    name: 'Vision',
    difficulty: 'Insane',
    difficultyColor: '#c084fc',
    songUrl: 'https://www.newgrounds.com/audio/listen/1418933',
    songTitle: 'Vision',
    artist: 'Newgrounds #1418933',
    bpm: 175,
    durationSeconds: 105,
    themeColor: '#c084fc',
    bgColor: '#160d33',
    description: 'The ultimate hive mind trance. Blistering rhythm, bullet-hell ant density, and extreme speed shifts.',
    spawnerCount: 6,
    maxAnts: 125,
    mechanicId: 'sonic_subwoofer',
    mechanicName: 'bass subwoofers',
    mechanicHint: 'click pulsing bass nodes to emit sonic shockwaves',
  },
  {
    id: 18,
    name: 'Neuro Colony',
    difficulty: 'Insane',
    difficultyColor: '#c084fc',
    songUrl: 'https://www.newgrounds.com/audio/listen/1419500',
    songTitle: 'Neuro Colony',
    artist: 'Newgrounds #1419500',
    bpm: 178,
    durationSeconds: 105,
    themeColor: '#a855f7',
    bgColor: '#140c30',
    description: 'Bio-electric neural synapses bridge across the anthill. Unyielding swarm pressure.',
    spawnerCount: 6,
    maxAnts: 130,
    mechanicId: 'cryo_barrels',
    mechanicName: 'cryo barrels',
    mechanicHint: 'click liquid nitrogen barrels to freeze pursuers in ice',
  },
  {
    id: 19,
    name: 'Synapse Overload',
    difficulty: 'Insane',
    difficultyColor: '#c084fc',
    songUrl: 'https://www.newgrounds.com/audio/listen/1420100',
    songTitle: 'Synapse Overload',
    artist: 'Newgrounds #1420100',
    bpm: 180,
    durationSeconds: 110,
    themeColor: '#c084fc',
    bgColor: '#180e38',
    description: 'Hyperdrive speed portals spawn continuously. Reaction times tested to the absolute limit.',
    spawnerCount: 6,
    maxAnts: 135,
    mechanicId: 'chrono_warp',
    mechanicName: 'chrono time warp',
    mechanicHint: 'click chrono spheres to slow time to matrix speed',
  },
  {
    id: 20,
    name: 'Hyperhive Genesis',
    difficulty: 'Insane',
    difficultyColor: '#c084fc',
    songUrl: 'https://www.newgrounds.com/audio/listen/1421000',
    songTitle: 'Hyperhive Genesis',
    artist: 'Newgrounds #1421000',
    bpm: 182,
    durationSeconds: 110,
    themeColor: '#a855f7',
    bgColor: '#150d32',
    description: 'Colony singularity. Saws bounce at maximum velocity while fire ants surround every angle.',
    spawnerCount: 7,
    maxAnts: 140,
    mechanicId: 'plasma_artillery',
    mechanicName: 'plasma cannons',
    mechanicHint: 'spam-click artillery cannons to barrage the hive with plasma',
  },

  // --- CRAZY (3 Levels - Harder Than Insane!) ---
  {
    id: 21,
    name: 'Apocalypse Hive',
    difficulty: 'Crazy',
    difficultyColor: '#f43f5e',
    songUrl: 'https://www.newgrounds.com/audio/listen/1422000',
    songTitle: 'Apocalypse Hive',
    artist: 'Newgrounds #1422000',
    bpm: 190,
    durationSeconds: 115,
    themeColor: '#f43f5e',
    bgColor: '#240616',
    description: 'Beyond Insane. 2 colossal Big Titan Ants command the swarm, unleashing pheromone surges to rally the little ones!',
    spawnerCount: 7,
    maxAnts: 155,
    mechanicId: 'titan_slayer',
    mechanicName: 'titan slayer',
    mechanicHint: 'click colossal titan ants directly to stagger & damage them',
  },
  {
    id: 22,
    name: 'Quantum Swarm',
    difficulty: 'Crazy',
    difficultyColor: '#f43f5e',
    songUrl: 'https://www.newgrounds.com/audio/listen/1423000',
    songTitle: 'Quantum Swarm',
    artist: 'Newgrounds #1423000',
    bpm: 200,
    durationSeconds: 120,
    themeColor: '#fb7185',
    bgColor: '#260718',
    description: 'Spatial distortion tear! 2 massive Big Ants coordinate a pincer flanking trap, summoning swift brood to overwhelm you.',
    spawnerCount: 8,
    maxAnts: 170,
    mechanicId: 'core_meltdown',
    mechanicName: 'hive meltdown',
    mechanicHint: 'spam-click overheating reactor cores to blast the hive',
  },
  {
    id: 23,
    name: 'Omega Extinction',
    difficulty: 'Crazy',
    difficultyColor: '#f43f5e',
    songUrl: 'https://www.newgrounds.com/audio/listen/1424000',
    songTitle: 'Omega Extinction',
    artist: 'Newgrounds #1424000',
    bpm: 215,
    durationSeconds: 125,
    themeColor: '#f43f5e',
    bgColor: '#2a0518',
    description: 'The final trial. 2 apex Titan Broodmothers shield and supercharge the little ants while saw tempests rage.',
    spawnerCount: 8,
    maxAnts: 185,
    mechanicId: 'queen_fortress',
    mechanicName: 'queen fortress',
    mechanicHint: 'spam-click central queen fortress while dodging elite broods',
  },
];

// Difficulty Ant Size configuration & metadata
export const DIFFICULTY_ANT_SCALING: Record<
  string,
  { base: number; worker: number; fire: number; acid: number; titan?: number; label: string; tag: string }
> = {
  Easy: { base: 6.0, worker: 6.0, fire: 6.8, acid: 7.2, label: 'Standard (1.0x)', tag: 'Normal Sized Ants' },
  Normal: { base: 7.5, worker: 7.5, fire: 8.3, acid: 8.8, label: 'Slightly Bigger (+25%)', tag: 'Slightly Bigger Ants' },
  Hard: { base: 9.2, worker: 9.2, fire: 10.0, acid: 10.6, label: 'Enlarged (+53%)', tag: 'Enlarged Swarm' },
  Harder: { base: 11.0, worker: 11.0, fire: 11.9, acid: 12.6, label: 'Heavy (+83%)', tag: 'Heavy Titan Swarm' },
  Insane: { base: 13.0, worker: 13.0, fire: 14.0, acid: 14.8, label: 'Colossal (+116%)', tag: 'Colossal Ants' },
  Crazy: { base: 6.5, worker: 6.5, fire: 7.2, acid: 7.6, titan: 22.0, label: '2 Big Ants + Little Swarm', tag: '2 Big Ants Supporting Swarm' },
};

// Special Free Mode (Endless Randomizer)
export const FREE_MODE_LEVEL: LevelConfig = {
  id: 999,
  name: 'Endless Free Mode',
  difficulty: 'Crazy',
  difficultyColor: '#60a5fa',
  songUrl: 'https://www.newgrounds.com/audio/listen/1418933',
  songTitle: 'Endless Randomizer',
  artist: 'Dynamic Shift Engine',
  bpm: 155,
  durationSeconds: 999999, // Endless!
  themeColor: '#3b82f6',
  bgColor: '#050c18',
  description: 'Endless survival mode where difficulty dynamically shifts every 15 seconds! The ultimate test of skill.',
  spawnerCount: 5,
  maxAnts: 120,
  isEndless: true,
  mechanicId: 'dynamic_chaos',
  mechanicName: 'dynamic chaos',
  mechanicHint: 'clickable defenses & interactive pods shift continuously',
};
